name: CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Setup toolchain
        uses: jdx/mise-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Build client
        run: bun run build:client
      - name: Build server
        run: bun run build:server
      - name: Build demo slides
        run: node bin/index.js build demo.typ
      - name: Prepare deployment directory
        run: |
          mkdir -p gh-pages
          cp -r dist/* gh-pages/
          cp -r schema gh-pages/schema
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "gh-pages"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
